### ISSUE TITLE
ldap authentication error

### ISSUE THREAD

**Issue by chacliff** [vesse/node-ldapauth-fork#17]
I hope your still maintaining this and can answer my question. 
i keep getting the same invalidCredentialsError no matter what credentials i have been putting in, i know the credentials i am using are correct does it not traverse the directories properly?

     LdapAuth = require('ldapauth-fork'); 
     var options = { 
	    url: "ldap://10.213.200.5", 
	     bindDn: "uid=adminuser, ou=company, o=directory",
	     bindCredentials: "password",
	    searchBase: "ou=company, o=directory",
	    searchFilter: "(uid={{username}})"
    };
    var auth = new LdapAuth(options); 
    var ldapValidate = function (username, password, callback){
	    console.log(username + " " + password); 
	    auth.authenticate(username, password, function(err, user){
		    if(err){
			    console.log("an error occured while authenticating"); 
			    console.log(err); 
		    }else{
			    console.log(user); 
		    }
		    callback(err, user); 
	    });
    };
    server.auth.strategy('psit-auth', 'basic', {validateFunc: ldapValidate });

**Comment by vesse** [comment]
Search and bind are pretty essential features of LDAP libraries so I'm tempted to think that the problem is neither in this module nor `ldapjs`, the actual LDAP client library used.

Have you verified the options? Could you add [log4js](https://github.com/vesse/node-ldapauth-fork/blob/ff234e6bea8ff1082f2a30862231a97c395c79f5/lib/ldapauth.js#L62-L64) or manually add some `console.log`s to see from which point the error comes from?

These should work if your options are correct:

Search for the user by username
```bash
ldapsearch -x -H ldap://10.213.200.5 \
  -D "uid=adminuser, ou=company, o=directory" \
  -b "ou=company, o=directory" -w "password" \
  "(uid=<PUT THE USER NAME HERE>)" dn
```

As the found user, see if bind works
```bash
ldapwhoami -x -H ldap://10.213.200.5 \ 
  -D "<put the DN returned by the above here>"
  -w "<put the password of the user here>"
```

**Comment by vesse** [comment]
OK, so problem is in the configuration. Triple check the admin DN that it is really what it should be (eg. there us usually no spaces between keys). I've used this same library with an Active Directory server on multiple occasions, although always with TLS enabled, eg. like this:

```javascript
var opts = {
  server: {
    url: 'ldaps://ad.corporate.com:636',
    bindDn: 'cn=non-person,ou=system,dc=corp,dc=corporate,dc=com',
    bindCredentials: 'secret',
    searchBase: 'dc=corp,dc=corporate,dc=com',
    searchFilter: '(&(objectcategory=person)(objectclass=user)(|(samaccountname={{username}})(mail={{username}})))',
    searchAttributes: ['displayName', 'mail'],
    tlsOptions: {
      ca: [
        fs.readFileSync('/path/to/root_ca_cert.crt')
      ]
    }
  }
};
```

**Comment by chacliff** [comment]
yeah it was just the bindDn that was the problem i ended up just doing bindDN: "username" and had it look for the username globally through the entire server. and putting the areas i wanted searches to occur on the search filter for the opts. 

    url: 'ldap://10.213.200.5:389', 
	    bindDn: "cgmus\\ldap_webapi_lib",
	    bindCredentials: "#######",
	    searchBase: "dc=cgmus, dc=local",
	    searchFilter: "(sAMAccountName={{username}})"


Your post did sort of help me once i installed OpenLdap and figured out the proper syntax and looked at more examples. 
P.S why don't you do a pull request to the original project, the original owner appears to still be active. If i get some time i might do a pull request on your project to update the documentation because its very unclear and i spent two days working on this part when it should of maybe taken me a day with additional functionality being added around it.

**Comment by vesse** [comment]
Cool. Yeah I know the documentation is not exceptional, I just forked the project for an urgent need back in the day and then kept on fixing the issues (last commit to the original project was made a year and a half ago). But really, the library just wraps `ldapjs` and most of the options are just passed forward to `ldapjs`, so you might as well look into [ldapjs documentation](http://ldapjs.org/client.html), especially because the basic parameters (bind credentials, search base, and filter) are core LDAP parameters and extensively documented elsewhere.

**Comment by chacliff** [comment]
That is true, the ldapjs library is much harder to understand though but is also poorly documented, That seems to be most of my experience with node/hapi. We all need to make an effort to document our plugins/apps more effectively for others future use.
