### ISSUE TITLE
Anonymous authentication?

### ISSUE THREAD

**Issue by aparticka** [vesse/node-ldapauth-fork#32]
I just logged in to my application without using a password and learned that the `authenticate` method doesn't require a password because it will just bind anonymously.

Is this really the intended behavior?

I can perform the check for an empty password myself, I was just wondering if this was missed somehow and others have the same security hole in their system.

**Comment by vesse** [comment]
A valid point probably - before 1.0.0  release `ldapjs` did require a password for `bind`, but this was removed there to be able to bind anonymously (mcavage/node-ldapjs#254). Since this library is an authentication library it probably should require user password like [passport-ldapauth](https://github.com/vesse/passport-ldapauth/blob/df03ccfe6542a7c9c3d9a1175fcadbd79bca5680/lib/passport-ldapauth/strategy.js#L136-L138) does.

**Comment by nchokoev** [comment]
I think the library should support anonymous binds. If the LDAP server is configured in such a way, the library should be still functional.
The server I'm trying to use the library with is configured this way and I can't use the library with blank user/pass.
The main purpose of the library is to provide functionality to authenticate an user to LDAP, and that should be the main focus, not restricting connectivity to LDAP...
