### ISSUE TITLE
Ldap auth error:unexpected number of  matches(10) 

### ISSUE THREAD

**Issue by sureshchouksey** [vesse/node-ldapauth-fork#35]
I am trying to connect ldap server using your library. The problem is i get the following error :

LDAP auth error:unexpected number of matches(10) for "CN=simple One,CN=Users,DC=test,DC=local" username

When i use library to connect to the ldap server using :

```javascript
var config = {
  ldap: {
    url: "ldap://54.227.207.201:389",
    bindDn: "CN=ritesh simplicity,CN=Users,DC=test,DC=local",
    bindCredentials: "p4$$w0rd@!",
    searchBase: "DC=test,DC=local",
    searchFilter: "(objectClass=user)"
  }
};


var ldap = new LdapAuth({
  url: config.ldap.url,
  bindDn: config.ldap.bindDn,
  bindCredentials: config.ldap.bindCredentials,
  searchBase: config.ldap.searchBase,
  searchFilter: config.ldap.searchFilter,
  //log4js: require('log4js'),
  cache: true
});
   

app.post('/process_post', urlencodedParser, function (req, res) {
   var username="CN="+req.body.first_name+",CN=Users,DC=test,DC=local";
   var password=req.body.last_name;

   ldap.authenticate(username, password, function (err, user) {
    if (err) {
      console.log("LDAP auth error: %s", err);
    }
    console.log("User Successful",user);
  });
})
```

Please guide me through the issue i am facing.

**Comment by vesse** [comment]
Your problem is that you are not using the username anywhere in the search filter. You search for `"(objectClass=user)"`, ie. every user in your LDAP, and that returns more than one results which is unaccepted for authentication. You need to add the `{{username}}` literal to the filter as [mentioned in options documentation](https://github.com/vesse/node-ldapauth-fork/blob/cc3c920bafaac6888cdaa2f02bd6b85ccba0bf15/lib/ldapauth.js#L52-L55), eg. `searchFilter : "(&(username={{username}})(objectClass=user))"` (where field `username` depends on your LDAP setup, for MS AD you would use `samaccountname`)
