### ISSUE TITLE
auth.on('error', function (err) .. is executed twice for each error

### ISSUE THREAD

**Issue by alexanderdevm** [vesse/node-ldapauth-fork#53]
I am testing ldapauth-fork against ldap url being unreachable and i have noticed that on "auth.on('error', function (err)" is executed twice on error.
`
var auth= new LdapAuth({
url: some_unreachable_url
...
}
`
`
auth.on('error', function (err) {
      console.log("hello");
}
`

In the example above with "hello" is printed twice.

**Comment by vesse** [comment]
Yes. That is because there are [two ldapjs clients](https://github.com/vesse/node-ldapauth-fork/blob/ce01b3a1a142bf1093fa64d20c05447f8656d2a5/lib/ldapauth.js#L107-L110) instantiated.

Two clients are needed because the so called admin client is used to locate the user. Usually anonymous searches are not allowed and thus a bound client is needed. The other client is needed for testing the user password - when an object is found with the admin client, the DN of that object together with the user provided password are used to bind the other client which verifies the password.
